spring.application.name=Capabilities
server.port=8081

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/capabilities_db
spring.r2dbc.username=postgres
spring.r2dbc.password=123

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:schema.sql